/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9ef50d1f-db0d-49d7-89d6-d585eb8abdb3",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_JTa6wo6nI",
    "aws_user_pools_web_client_id": "6iqgi6c6gl3d1r5abl5bc06dsg",
    "oauth": {}
};


export default awsmobile;
